[general]
enable_bucket = true

[[datasets]]
resolution = 512
batch_size = 1

  [[datasets.subsets]]
  image_dir = '/mnt/c/Users/jcook/git/kohya_ss/train_data/image/1_food'
  caption_extension = '.txt'
  num_repeats = 1

[network_args]
network_module = 'networks.lora'
network_dim = 32
network_alpha = 16

[optimizer_args]
learning_rate = 0.0001
lr_scheduler = 'cosine_with_restarts'
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1

[training_args]
max_train_epochs = 10
save_every_n_epochs = 2
save_model_as = 'safetensors'
save_last_n_epochs = 3
keep_tokens = 0
clip_skip = 2
prior_loss_weight = 1
max_token_length = 225
xformers = true
max_data_loader_n_workers = 0
persistent_data_loader_workers = false
seed = 42
mixed_precision = 'fp16'

[sample_args]
sample_every_n_epochs = 1
sample_prompts = "a photo of food style ramen"

[saving_args]
output_dir = './output'
output_name = 'food_lora'
save_precision = 'fp16'